/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedWeeklyReportRouteImport } from './routes/_authenticated/weekly-report'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPeFirmsRouteImport } from './routes/_authenticated/pe-firms'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCandidatesRouteImport } from './routes/_authenticated/candidates'
import { Route as AuthenticatedActivityLogRouteImport } from './routes/_authenticated/activity-log'
import { Route as AuthenticatedCandidatesIdRouteImport } from './routes/_authenticated/candidates.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWeeklyReportRoute =
  AuthenticatedWeeklyReportRouteImport.update({
    id: '/weekly-report',
    path: '/weekly-report',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPeFirmsRoute = AuthenticatedPeFirmsRouteImport.update({
  id: '/pe-firms',
  path: '/pe-firms',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCandidatesRoute = AuthenticatedCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActivityLogRoute =
  AuthenticatedActivityLogRouteImport.update({
    id: '/activity-log',
    path: '/activity-log',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCandidatesIdRoute =
  AuthenticatedCandidatesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCandidatesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activity-log': typeof AuthenticatedActivityLogRoute
  '/candidates': typeof AuthenticatedCandidatesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/import': typeof AuthenticatedImportRoute
  '/pe-firms': typeof AuthenticatedPeFirmsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/weekly-report': typeof AuthenticatedWeeklyReportRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/candidates/$id': typeof AuthenticatedCandidatesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activity-log': typeof AuthenticatedActivityLogRoute
  '/candidates': typeof AuthenticatedCandidatesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/import': typeof AuthenticatedImportRoute
  '/pe-firms': typeof AuthenticatedPeFirmsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/weekly-report': typeof AuthenticatedWeeklyReportRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/candidates/$id': typeof AuthenticatedCandidatesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/activity-log': typeof AuthenticatedActivityLogRoute
  '/_authenticated/candidates': typeof AuthenticatedCandidatesRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/pe-firms': typeof AuthenticatedPeFirmsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/weekly-report': typeof AuthenticatedWeeklyReportRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/candidates/$id': typeof AuthenticatedCandidatesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/activity-log'
    | '/candidates'
    | '/dashboard'
    | '/import'
    | '/pe-firms'
    | '/settings'
    | '/weekly-report'
    | '/auth/callback'
    | '/candidates/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/activity-log'
    | '/candidates'
    | '/dashboard'
    | '/import'
    | '/pe-firms'
    | '/settings'
    | '/weekly-report'
    | '/auth/callback'
    | '/candidates/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/activity-log'
    | '/_authenticated/candidates'
    | '/_authenticated/dashboard'
    | '/_authenticated/import'
    | '/_authenticated/pe-firms'
    | '/_authenticated/settings'
    | '/_authenticated/weekly-report'
    | '/auth/callback'
    | '/_authenticated/candidates/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/weekly-report': {
      id: '/_authenticated/weekly-report'
      path: '/weekly-report'
      fullPath: '/weekly-report'
      preLoaderRoute: typeof AuthenticatedWeeklyReportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pe-firms': {
      id: '/_authenticated/pe-firms'
      path: '/pe-firms'
      fullPath: '/pe-firms'
      preLoaderRoute: typeof AuthenticatedPeFirmsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/candidates': {
      id: '/_authenticated/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof AuthenticatedCandidatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/activity-log': {
      id: '/_authenticated/activity-log'
      path: '/activity-log'
      fullPath: '/activity-log'
      preLoaderRoute: typeof AuthenticatedActivityLogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/candidates/$id': {
      id: '/_authenticated/candidates/$id'
      path: '/$id'
      fullPath: '/candidates/$id'
      preLoaderRoute: typeof AuthenticatedCandidatesIdRouteImport
      parentRoute: typeof AuthenticatedCandidatesRoute
    }
  }
}

interface AuthenticatedCandidatesRouteChildren {
  AuthenticatedCandidatesIdRoute: typeof AuthenticatedCandidatesIdRoute
}

const AuthenticatedCandidatesRouteChildren: AuthenticatedCandidatesRouteChildren =
  {
    AuthenticatedCandidatesIdRoute: AuthenticatedCandidatesIdRoute,
  }

const AuthenticatedCandidatesRouteWithChildren =
  AuthenticatedCandidatesRoute._addFileChildren(
    AuthenticatedCandidatesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedActivityLogRoute: typeof AuthenticatedActivityLogRoute
  AuthenticatedCandidatesRoute: typeof AuthenticatedCandidatesRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedPeFirmsRoute: typeof AuthenticatedPeFirmsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWeeklyReportRoute: typeof AuthenticatedWeeklyReportRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedActivityLogRoute: AuthenticatedActivityLogRoute,
  AuthenticatedCandidatesRoute: AuthenticatedCandidatesRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedPeFirmsRoute: AuthenticatedPeFirmsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWeeklyReportRoute: AuthenticatedWeeklyReportRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
